function [subjCft, maskCft] = get_subTC(id, session, data_type, task, ...
                                        max_frame_num, root_path, ...
                                        if_normalize, if_smooth)
    % prepare parameters
    if ~exist('if_normalize','var') if_normalize = 0; end
    % if ~exist('if_ica_fix','var') if_ica_fix = 0; end

    sigma = 4;
    if ~exist('if_smooth','var') 
        if_smooth = 0;
    elseif if_smooth == 1 
        sigma = 4;
    elseif if_smooth > 1
        sigma = if_smooth;
    end 

    
    % task or rest fMRI
    if strcmp(task,'REST1') || strcmp(task,'REST2')
        fMRI_name = 'rfMRI';
        folder_name = fullfile(root_path, 'HCP100_rest');
        hp = 'hp2000';
    else
        fMRI_name = 'tfMRI';
        folder_name = fullfile(root_path, 'HCP100_task');
        hp = 'hp0';
    end

    % ----- build fMRI original and smoothed data path ----- 
    surf_L_path = fullfile(root_path, 'HCP100_structual', ...
                    id, 'MNINonLinear', 'fsaverage_LR32k', ...
                    [id '.L.midthickness_MSMAll.32k_fs_LR.surf.gii']);
    surf_R_path = fullfile(root_path, 'HCP100_structual', ...
                    id, 'MNINonLinear', 'fsaverage_LR32k', ...
                    [id '.R.midthickness_MSMAll.32k_fs_LR.surf.gii']);
    
    if strcmp(data_type,'fMRI')
        original_path = fullfile(folder_name, ...
                            id, 'MNINonLinear', 'Results', ...
                            [fMRI_name '_' task '_' session], ...
                            [fMRI_name '_' task '_' session ...
                            '_Atlas_MSMAll_' hp '_clean_rclean_tclean.dtseries.nii']);
        smooth_path = fullfile(folder_name, ...
                            id, 'MNINonLinear', 'Results', ...
                            [fMRI_name '_' task '_' session], ...
                            [fMRI_name '_' task '_' session ...
                            '_Atlas_MSMAll_' hp '_clean_rclean_tclean' ...
                            '_smooth_' int2str(sigma)  '.dtseries.nii']);
        if ~exist(smooth_path, 'file') && if_smooth > 0
            disp(['Smoothed fMRI data not exist. ' ...
                'Performing spatial smoothing sub-' id]);
            system(['wb_command -cifti-smoothing ' original_path  ' ' ...
                int2str(sigma) ' ' int2str(sigma) ' -fwhm COLUMN ' ...
                smooth_path ' -left-surface ' surf_L_path ...
                ' -right-surface ' surf_R_path]);
        end       
        
    elseif strcmp(data_type,'fMRI2run')
        original_path.LR = fullfile(folder_name, ...
                            id, 'MNINonLinear', 'Results', ...
                            [fMRI_name '_' task '_LR'], ...
                            [fMRI_name '_' task '_LR' ...
                            '_Atlas_MSMAll_' hp '_clean_rclean_tclean.dtseries.nii']);
        original_path.RL = fullfile(folder_name, ...
                            id, 'MNINonLinear', 'Results', ...
                            [fMRI_name '_' task '_RL'], ...
                            [fMRI_name '_' task '_RL'  ...
                            '_Atlas_MSMAll_' hp '_clean_rclean_tclean.dtseries.nii']);
        smooth_path.LR = fullfile(folder_name, ...
                            id, 'MNINonLinear', 'Results', ...
                            [fMRI_name '_' task '_LR' ], ...
                            [fMRI_name '_' task '_LR' ...
                            '_Atlas_MSMAll_' hp '_clean_rclean_tclean' ...
                            '_smooth_' int2str(sigma)  '.dtseries.nii']);
        smooth_path.RL = fullfile(folder_name, ...
                            id, 'MNINonLinear', 'Results', ...
                            [fMRI_name '_' task '_RL' ], ...
                            [fMRI_name '_' task '_RL' ...
                            '_Atlas_MSMAll_' hp '_clean_rclean_tclean' ...
                            '_smooth_' int2str(sigma)  '.dtseries.nii']);
        if ~exist(smooth_path.LR, 'file') && if_smooth > 0
            disp(['Smoothed fMRI data not exist. ' ...
                'Performing spatial smoothing sub-' id ' LR']);
            system(['wb_command -cifti-smoothing ' original_path.LR ' -fwhm ' ...
                int2str(sigma) ' ' int2str(sigma) ' COLUMN ' ...
                smooth_path.LR ' -left-surface ' surf_L_path ...
                ' -right-surface ' surf_R_path ]);
        end
        if ~exist(smooth_path.RL, 'file') && if_smooth > 0
            disp(['Smoothed fMRI data not exist. ' ...
                'Performing spatial smoothing sub-' id ' RL']);
            system(['wb_command -cifti-smoothing ' original_path.RL ' -fwhm ' ...
                int2str(sigma) ' ' int2str(sigma) ' COLUMN ' ...
                smooth_path.RL ' -left-surface ' surf_L_path ...
                ' -right-surface ' surf_R_path ]);
        end
    end
    
    % ----- get fMRI data ----- 
    if if_smooth > 0
        data_path = smooth_path;
    else
        data_path = original_path;
    end
    [subjCft, maskCft, num_vert] = read_data(data_path, data_type, max_frame_num);

    % ----- subTC normalization -----
    % NOTICE: must do normalization before concatenation, otherwise LR traj
    % will be separated from RL traj.
    subjCft_LR = subjCft(maskCft, 1:max_frame_num);
    subjCft_RL = subjCft(maskCft, (max_frame_num+1):end);
    if if_normalize == 1
        subjCft(maskCft, :) = [normalize(subjCft_LR, 2) normalize(subjCft_RL, 2)];
    elseif if_normalize == 2 % smooth - mean
        subjCft(maskCft, :) = [subjCft_LR - mean(subjCft_LR,2) ...
                                subjCft_RL - mean(subjCft_RL,2)];
    else % DEFALUT, if_normalize = 0
        subjCft(maskCft, :) = [subjCft_LR, subjCft_RL];
    end
    
end